import "./globals.css";
import { Poppins } from "next/font/google";
import { QueryProvider } from "@/components/Providers/QueryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "DT Money",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={poppins.variable}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
